name = "svg-studio"
compatibility_date = "2024-08-13"

[build]
command = "npm run build"
cwd = "/"
watch_dir = "src"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]

[build.upload]
format = "directory"
dir = "./out"